/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module counter(clk, reset, count);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input clk;
  output [3:0] count;
  reg [3:0] count;
  input reset;
  assign _00_[0] = ~(count[0] | reset);
  assign _01_ = ~reset;
  assign _02_ = ~(count[0] ^ count[1]);
  assign _00_[1] = _01_ & ~(_02_);
  assign _03_ = ~(count[0] & count[1]);
  assign _04_ = _03_ ^ count[2];
  assign _00_[2] = _01_ & ~(_04_);
  assign _05_ = _03_ | ~(count[2]);
  assign _06_ = _05_ ^ count[3];
  assign _00_[3] = _01_ & ~(_06_);
  always @(posedge clk)
      count[0] <= _00_[0];
  always @(posedge clk)
      count[1] <= _00_[1];
  always @(posedge clk)
      count[2] <= _00_[2];
  always @(posedge clk)
      count[3] <= _00_[3];
endmodule
