/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux.v:1" *)
module mux(i0, i1, sel, y);
  (* src = "mux.v:1" *)
  input i0;
  (* src = "mux.v:1" *)
  input i1;
  (* src = "mux.v:1" *)
  input sel;
  (* src = "mux.v:1" *)
  output y;
  assign y = sel ? i1 : i0;
endmodule
