/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:1" *)
module comp_case(sel, a, b, c, y);
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:3" *)
  wire _00_;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:4" *)
  wire _01_;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:5" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:2" *)
  wire _06_;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:2" *)
  wire _07_;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:6" *)
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:3" *)
  input a;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:4" *)
  input b;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:5" *)
  input c;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:2" *)
  input [1:0] sel;
  (* src = "/workspaces/vsd-rtl/Module 5/comp_case.v:6" *)
  output y;
  sky130_fd_sc_hd__nor3_1 _15_ (
    .A(_07_),
    .B(_06_),
    .C(_00_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2b_1 _16_ (
    .A(_02_),
    .B_N(_07_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2b_1 _17_ (
    .A_N(_07_),
    .B(_01_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a211oi_1 _18_ (
    .A1(_06_),
    .A2(_05_),
    .B1(_04_),
    .C1(_03_),
    .Y(_08_)
  );
  assign _07_ = sel[1];
  assign _06_ = sel[0];
  assign _01_ = b;
  assign _02_ = c;
  assign _00_ = a;
  assign y = _08_;
endmodule
