/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:1" *)
module demux_case(din, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:2" *)
  wire _04_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:3" *)
  wire _05_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:3" *)
  wire _06_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:4" *)
  wire _07_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:4" *)
  wire _08_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:4" *)
  wire _09_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:4" *)
  wire _10_;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:2" *)
  input din;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:3" *)
  input [1:0] sel;
  (* src = "/workspaces/vsd-rtl/Module 5/demux_case.v:4" *)
  output [3:0] y;
  sky130_fd_sc_hd__nor3b_1 _11_ (
    .A(_06_),
    .B(_05_),
    .C_N(_04_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and3b_1 _12_ (
    .A_N(_05_),
    .B(_04_),
    .C(_06_),
    .X(_09_)
  );
  sky130_fd_sc_hd__and3b_1 _13_ (
    .A_N(_06_),
    .B(_05_),
    .C(_04_),
    .X(_08_)
  );
  sky130_fd_sc_hd__and3_1 _14_ (
    .A(_06_),
    .B(_05_),
    .C(_04_),
    .X(_10_)
  );
  assign _06_ = sel[1];
  assign _05_ = sel[0];
  assign _04_ = din;
  assign y[0] = _07_;
  assign y[2] = _09_;
  assign y[1] = _08_;
  assign y[3] = _10_;
endmodule
