/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module dff_submodule(clk, d, q);
  input clk;
  input d;
  output q;
  reg q;
  always @(posedge clk)
      q <= d;
endmodule

module top_hierarchical(clk, d, q);
  input clk;
  input d;
  output q;
  dff_submodule u1 (
    .clk(clk),
    .d(d),
    .q(q)
  );
endmodule
